apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oneplatform-apps
spec:
  destination:
    name: ''
    namespace: argo
    server: 'https://kubernetes.default.svc'
  source:
    path: clusters/argocd-autopilot/argo-workflow
    repoURL: 'git@github.com:seakayone/kikd.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
