apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argo
  namespace: argo
spec:
  destinations:
    - namespace: argo
      server: https://kubernetes.default.svc
  sourceRepos:
    - git@github.com:seakayone/kikd.git
